// blog_back/src/pages/Music/subpages/MusicItem/MusicItem.vue
<template>
  <div class="MusicItem" @click.stop="goEdit">
      <span>{{item.songName}}</span>
      <span>{{item.singer}}</span>
      <span>{{item.categoryName}}</span>
      <span class="image">
        <img width="50" height="50" alt="" :src="musicCoverPrefix+item.cover+'?v='+new Date().getTime()"/>
      </span>
      <span @click.stop><input class="opearcheck" @click.stop type="checkbox" :value="item.id"></span>
  </div>
</template>

<script type="text/ecmascript-6">
  export default {  
    props: {
      item: {
        type: Object,
        default: null
      },
      index: {
        type: Number,
        default: 0
      }
    },
    data() {
      return {
        musicCoverPrefix: global.musicCoverUrl
      }
    },
    methods: {
      goEdit() {
        this.$router.push('/music/edit/'+this.item.id)
      }
    }
  }
</script>

<style lang="scss" scoped type="text/css">
  @import "./MusicItem.scss";
</style>

// blog_front/src/pages/Music/subpages/MusicItem/MusicItem.jsx
import React, { Component } from 'react';
import PureRenderMixin from 'react-addons-pure-render-mixin'
import { withRouter } from 'react-router-dom'

import './MusicItem.less'
import './MMusicItem.less'

class MusicItem extends React.Component {

	constructor(props,context) {
		super(props,context)
	}

	componentDidMount() {
	  
	}

	selectItem() {
		this.props.selectItemFn(this.props.item,this.props.index);
	}

	render() {
		return (
			<div className="MusicItem" onClick={this.selectItem.bind(this)}>
				<div className="wrap">
					<img className="coverImg" alt="" src={global.musicCoverPrefix+this.props.item.cover+'?v='+new Date().getTime()}/>
					<div className="info">
						<h4 className="songName">{this.props.item.songName}</h4>
						<p className="singer">{this.props.item.singer}</p>
					</div>
				</div>
        	</div>
        )
	}
}

export default withRouter(MusicItem)
